=== tetherless-world/POEM/rcads/data/xml/10_Instruments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0031_0_Instruments" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0031_0_Instruments">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="InstrumentID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADqDec7QN1lTaMTX+lsaExNAAAAACCQXjdVi+ZAAAAAAAAAAAAxADAA
XwBJAG4AcwB0AHIAdQBtAGUAbgB0AHMAAAAAAAAAmOeP2vBe8EWOnxZmFamv0gAA
AAAEJkk104XmQAAAAAAAAAAAMAAzAF8AQQBjAHQAaQB2AGkAdABpAGUAcwAAAAAA
AAAi5o7jDB6HT71BBQPyfhTQBwAAAOoN5ztA3WVNoxNf6WxoTE1JAG4AcwB0AHIA
dQBtAGUAbgB0AEkARAAAAAAAAABwWiKMxR+BQbsc/02HNDJVBwAAAOoN5ztA3WVN
oxNf6WxoTE1JAG4AcwB0AHIAdQBtAGUAbgB0AE4AYQBtAGUAAAAAAAAAg9GQbTtr
xkSu+81/sfvB3gAAAAAmR4rvMmLmQAAAAAAAAAAAMAAwAF8ASQBuAHMAdAByAHUA
bQBlAG4AdABGAGEAbQBpAGwAaQBlAHMAAAAAAAAAfvP+yRf3Kk+opICNFp/TcgcA
AACD0ZBtO2vGRK77zX+x+8HeRgBhAG0AaQBsAHkASQBEAAAAAAAAANSpimL3ydhM
jzRpbI8hCTAHAAAAg9GQbTtrxkSu+81/sfvB3kkAbgBzAHQAcgB1AG0AZQBuAHQA
RgBhAG0AaQBsAHkAAAAAAAAATweYzPB8D0WsL4Ah2jmZ5QcAAADqDec7QN1lTaMT
X+lsaExNSQBuAHMAdAByAHUAbQBlAG4AdABGAGEAbQBpAGwAeQAAAAAAAABqYTCf
kURZSY48cDc8kVA3AAAAAIcmit2xiOZAAAAAAAAAAAA5ADAAXwBMAGEAbgBnAHUA
YQBnAGUAcwAAAAAAAACrMY2PjWV6Tp3M5t6QklJQBwAAAGphMJ+RRFlJjjxwNzyR
UDdMAGEAbgBnAHUAYQBnAGUASQBEAAAAAAAAAHO1cvlc2OxAvFlWCyVKOUUHAAAA
amEwn5FEWUmOPHA3PJFQN0wAYQBuAGcAdQBhAGcAZQAAAAAAAABj0W9f+lAXQqzS
+8/zGHUaBwAAAOoN5ztA3WVNoxNf6WxoTE1MAGEAbgBnAHUAYQBnAGUAAAAAAAAA
BYffSRncwkKaQWnCTfb5FgAAAABSudge9HfmQAAAAAAAAAAAOQAxAF8ASQBuAGYA
bwByAG0AYQBuAHQAAAAAAAAA8EP3O1IYREWloR6q+Wxp1gcAAAAFh99JGdzCQppB
acJN9vkWSQBuAGYAbwByAG0AYQBuAHQASQBEAAAAAAAAAJ0qVWkp7/VKhF6G/kHM
AUYHAAAABYffSRncwkKaQWnCTfb5FkkAbgBmAG8AcgBtAGEAbgB0AAAAAAAAAB15
/Hg2YjdIlwYeqLeb/BAHAAAA6g3nO0DdZU2jE1/pbGhMTUkAbgBmAG8AcgBtAGEA
bgB0AAAAAAAAAB6JKP7wpqlEjv9Z0L4IHloHAAAA6g3nO0DdZU2jE1/pbGhMTUEA
bgBuAG8AdABhAHQAaQBvAG4AAAAAAAAAgkWKQw4RCkyIQhFyLi2DLwcAAADqDec7
QN1lTaMTX+lsaExNRABlAHAAcgBlAGMAYQB0AGUAZAAAAAAAAADjBL3UmhESSoTM
KmkBgIkPBwAAAOoN5ztA3WVNoxNf6WxoTE1BAHUAdABoAG8AcgBpAHoAZQBkAAAA
AAAAAMd2myq84SZEj2x8rvbPsn4HAAAA6g3nO0DdZU2jE1/pbGhMTVIAZQBhAGQA
UgBpAGcAaAB0AHQAbwBMAGUAZgB0AAAAAAAAANe3cAu7KIxMoTjq1ISAXMwHAAAA
6g3nO0DdZU2jE1/pbGhMTVUAbgBhAHYAYQBpAGwAYQBiAGwAZQAoAE4AbwB0AEcA
ZQBuAGUAcgBhAHQAZQBkACkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAA
AAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="SubdatasheetName" type="10" value="Table.03_Activities"/>
<od:tableProperty name="LinkMasterFields" type="10" value="InstrumentID"/>
<od:tableProperty name="GUID" type="9" value="6g3nO0DdZU2jE1/pbGhMTQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="InstrumentID" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="IuaO4wweh0+9QQUD8n4U0A==
"/>
<od:fieldProperty name="Description" type="10" value="[maps to POEM: Psychometric Questionnaire]"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="InstrumentName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2445"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="cFoijMUfgUG7HP9NhzQyVQ==
"/>
<od:fieldProperty name="Description" type="10" value="Human readable common name for the questionnaire"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="InstrumentFamily" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2400"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [00_InstrumentFamilies].FamilyID, [00_InstrumentFamilies].InstrumentFamily FROM 00_InstrumentFamilies ORDER BY [InstrumentFamily]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="TweYzPB8D0WsL4Ah2jmZ5Q==
"/>
<od:fieldProperty name="Description" type="10" value="This is the VSTO-I Instrument Family"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Language" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2190"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [90_Languages].[LanguageID], [90_Languages].[Language] FROM 90_Languages ORDER BY [Language]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Y9FvX/pQF0Ks0vvP8xh1Gg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Informant" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [91_Informant].[InformantID], [91_Informant].[Informant] FROM 91_Informant ORDER BY [InformantID]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="HXn8eDZiN0iXBh6ot5v8EA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Annotation" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="5910"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Hoko/vCmqUSO/1nQvggeWg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Deprecated" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Was previously authorized, but now is not to be published or used. Must be maintained for provenance queries and for some other queries. Would not be in Publisher or Scoring Applications."/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="gkWKQw4RCkyIQhFyLi2DLw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Authorized" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4wS91JoREkqEzCppAYCJDw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Was never authorized. Not to be published or used. Would not be in Provenance or Publisher or Scoring Applications. Availble for custom analysis and inspection. Do not change to No when deprecating."/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ReadRighttoLeft" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1960"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="x3abKrzhJkSPbHyu9s+yfg==
"/>
<od:fieldProperty name="Description" type="10" value="12-2025: maybe move this to language table eventually"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Unavailable_x0028_NotGenerated_x0029_" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3150"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="17dwC7sojEyhOOrUhIBczA==
"/>
<od:fieldProperty name="Description" type="10" value="do we need this field?"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/10_Instruments.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="10_Instruments.xsd" generated="2026-06-30T12:12:49">
<_x0031_0_Instruments>
<InstrumentID>1</InstrumentID>
<InstrumentName>RCADS-47-Y-EN</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>1</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>2</InstrumentID>
<InstrumentName>RCADS-47-CG-EN</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>1</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>3</InstrumentID>
<InstrumentName>RCADS-25-Y-EN</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>1</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>4</InstrumentID>
<InstrumentName>RCADS-25-CG-EN</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>1</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>5</InstrumentID>
<InstrumentName>RCADS-47-Y-DE</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>9</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>6</InstrumentID>
<InstrumentName>RCADS-47-CG-DE</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>9</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>7</InstrumentID>
<InstrumentName>RCADS-25-Y-DE</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>9</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>8</InstrumentID>
<InstrumentName>RCADS-25-CG-DE</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>9</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>9</InstrumentID>
<InstrumentName>RCADS-47-Y-DA</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>4</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>10</InstrumentID>
<InstrumentName>RCADS-47-CG-DA</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>4</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>11</InstrumentID>
<InstrumentName>RCADS-25-Y-DA</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>4</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>12</InstrumentID>
<InstrumentName>RCADS-25-CG-DA</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>4</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>1</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>13</InstrumentID>
<InstrumentName>RCADS-47-Y-FR-FR-1</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>8</Language>
<Informant>1</Informant>
<Annotation>OG Bouvard version - has empirical study validating this version</Annotation>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>14</InstrumentID>
<InstrumentName>RCADS-47-CG-FR-CA-1</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>8</Language>
<Informant>2</Informant>
<Annotation>Chantal Caron et al 2018</Annotation>
<Deprecated>1</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>15</InstrumentID>
<InstrumentName>RCADS-25-Y-FR-FR-1</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>8</Language>
<Informant>1</Informant>
<Annotation>RCADS team generated</Annotation>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>16</InstrumentID>
<InstrumentName>RCADS-25-CG-FR-FR-1</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>8</Language>
<Informant>2</Informant>
<Annotation>No items; Based on Boustani update of France French version</Annotation>
<Deprecated>1</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>1</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>17</InstrumentID>
<InstrumentName>RCADS-47-Y-ES</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>21</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>18</InstrumentID>
<InstrumentName>RCADS-47-CG-ES</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>21</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>19</InstrumentID>
<InstrumentName>RCADS-25-Y-ES</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>21</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>20</InstrumentID>
<InstrumentName>RCADS-25-CG-ES</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>21</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>0</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>21</InstrumentID>
<InstrumentName>RCADS-47-Y-AR</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>2</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>1</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>22</InstrumentID>
<InstrumentName>RCADS-47-CG-AR</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>2</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>1</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>23</InstrumentID>
<InstrumentName>RCADS-25-Y-AR</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>2</Language>
<Informant>1</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>1</ReadRighttoLeft>
<Unavailable_x0028_NotGenerated_x0029_>0</Unavailable_x0028_NotGenerated_x0029_>
</_x0031_0_Instruments>
<_x0031_0_Instruments>
<InstrumentID>24</InstrumentID>
<InstrumentName>RCADS-25-CG-AR</InstrumentName>
<InstrumentFamily>1</InstrumentFamily>
<Language>2</Language>
<Informant>2</Informant>
<Deprecated>0</Deprecated>
<Authorized>0</Authorized>
<ReadRighttoLeft>1</ReadRighttoLeft>
